#!/bin/sh
# Run the Cyrius benchmark suite, append results to bench-history.csv, and
# regenerate BENCHMARKS.md. Ported from the cargo-bench era to cyrius bench.
#
# Usage: ./scripts/bench-history.sh
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HISTORY="$REPO_ROOT/bench-history.csv"
MD="$REPO_ROOT/BENCHMARKS.md"
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)
BRANCH=$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null || echo unknown)

[ -f "$HISTORY" ] || echo "timestamp,commit,branch,benchmark,min_ns,avg_ns" > "$HISTORY"

# cyrius bench prints build chatter + DCE notes before the result lines; each
# result line looks like: "  name: 5us avg (min=2us max=153us) [100000 iters]".
RAW=$(cd "$REPO_ROOT" && cyrius bench tests/varna.bcyr 2>&1)

OUT=$(printf '%s\n' "$RAW" \
    | grep -E '^[[:space:]]+[a-zA-Z_][a-zA-Z0-9_]*: .* avg \(')

if [ -z "$OUT" ]; then
    echo "error: no benchmark result lines captured" >&2
    printf '%s\n' "$RAW" >&2
    exit 1
fi

# cyrius >=6.5.19 measures what one clock read costs on this host and subtracts
# it from every sample, announcing it as
#   "  [timer floor 1.403us per clock read, measured; subtracted from every sample]"
# The floor is a property of the box's clocksource and moves between reboots, so
# record it next to the numbers: rows measured under different floors are not
# directly comparable. Older harnesses print no such line.
FLOOR=$(printf '%s\n' "$RAW" \
    | sed -n 's/^[[:space:]]*\[timer floor \([^ ]*\) per clock read.*/\1/p' | head -1)
[ -n "$FLOOR" ] || FLOOR="unreported (pre-6.5.19 harness)"

TOOLCHAIN=$(cyrius version 2>/dev/null | head -1 | awk '{print $2}')
[ -n "$TOOLCHAIN" ] || TOOLCHAIN="unknown"

printf '%s\n' "$OUT" | awk \
    -v ts="$TS" -v commit="$COMMIT" -v branch="$BRANCH" \
    -v hist="$HISTORY" -v md="$MD" -v floor="$FLOOR" -v toolchain="$TOOLCHAIN" '
function to_ns(v,   num, unit) {
    # cyrius >=6.3 prints fractional units ("1.396us"); strip the trailing unit
    # letters for the number and all digits/decimal point for the unit so both
    # integer ("5us") and decimal ("36.806us") forms parse correctly.
    num = v; gsub(/[a-z]+$/, "", num)
    unit = v; gsub(/[0-9.]+/, "", unit)
    if (unit == "us") return int(num * 1000 + 0.5)
    if (unit == "ms") return int(num * 1000000 + 0.5)
    return int(num + 0.5)   # ns (and any unitless fallback)
}
BEGIN {
    print "# Benchmarks"                                                        > md
    print ""                                                                   >> md
    print "Generated by `./scripts/bench-history.sh` (`cyrius bench tests/varna.bcyr`)." >> md
    print "History in `bench-history.csv`. `min` is the most representative"   >> md
    print "per-op figure (the bump allocator never frees, so `avg` carries"    >> md
    print "accumulating alloc overhead)."                                      >> md
    print ""                                                                   >> md
    print "Latest: **" ts "** commit `" commit "` on cyrius `" toolchain "`"   >> md
    print ""                                                                   >> md
    print "Timer floor: **" floor "** per clock read (measured on this host,"  >> md
    print "subtracted from every sample). Cyrius >=6.5.19 calibrates this at"  >> md
    print "runtime; the value is a property of the host clocksource and"       >> md
    print "moves between reboots, so rows recorded under different floors are" >> md
    print "not directly comparable."                                           >> md
    print ""                                                                   >> md
    print "> **History discontinuity.** Rows in `bench-history.csv` before"    >> md
    print "> 2026-08-27 were measured by the pre-6.5.19 harness, which wrapped">> md
    print "> a clock pair around *every* iteration and so floored all 18 rows" >> md
    print "> at roughly two clock reads (the ~419ns/489ns/907ns plateaus)."    >> md
    print "> Since cyrius 6.5.19 `bench_run` sizes its own batches and nets"   >> md
    print "> out the measured floor, so sub-microsecond rows finally resolve." >> md
    print "> Do not read the step between those regimes as a code change."     >> md
    print ""                                                                   >> md
    print "| Benchmark | min | avg |"                                          >> md
    print "|-----------|-----|-----|"                                          >> md
}
{
    name = $1; gsub(/:/, "", name)
    avg  = $2
    minv = $4; gsub(/^\(min=/, "", minv)
    printf "%s,%s,%s,%s,%s,%s\n", ts, commit, branch, name, to_ns(minv), to_ns(avg) >> hist
    printf "| `%s` | %s | %s |\n", name, minv, avg                            >> md
}
'

echo "Wrote $HISTORY and $MD"
