#!/bin/sh
# Run the Cyrius benchmark suite, append results to bench-history.csv, and
# regenerate BENCHMARKS.md. Ported from the cargo-bench era to cyrius bench.
#
# Usage: ./scripts/bench-history.sh
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HISTORY="$REPO_ROOT/bench-history.csv"
MD="$REPO_ROOT/BENCHMARKS.md"
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)
BRANCH=$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null || echo unknown)

[ -f "$HISTORY" ] || echo "timestamp,commit,branch,benchmark,min_ns,avg_ns" > "$HISTORY"

# cyrius bench prints build chatter + DCE notes before the result lines; each
# result line looks like: "  name: 5us avg (min=2us max=153us) [100000 iters]".
OUT=$(cd "$REPO_ROOT" && cyrius bench tests/varna.bcyr 2>&1 \
    | grep -E '^[[:space:]]+[a-zA-Z_][a-zA-Z0-9_]*: .* avg \(')

if [ -z "$OUT" ]; then
    echo "error: no benchmark result lines captured" >&2
    exit 1
fi

printf '%s\n' "$OUT" | awk \
    -v ts="$TS" -v commit="$COMMIT" -v branch="$BRANCH" \
    -v hist="$HISTORY" -v md="$MD" '
function to_ns(v,   num, unit) {
    num = v; gsub(/[a-z]+$/, "", num)
    unit = v; gsub(/^[0-9]+/, "", unit)
    if (unit == "ns") return num
    if (unit == "us") return num * 1000
    if (unit == "ms") return num * 1000000
    return num
}
BEGIN {
    print "# Benchmarks"                                                        > md
    print ""                                                                   >> md
    print "Generated by `./scripts/bench-history.sh` (`cyrius bench tests/varna.bcyr`)." >> md
    print "History in `bench-history.csv`. `min` is the most representative"   >> md
    print "per-op figure (the bump allocator never frees, so `avg` carries"    >> md
    print "accumulating alloc overhead)."                                      >> md
    print ""                                                                   >> md
    print "Latest: **" ts "** commit `" commit "`"                             >> md
    print ""                                                                   >> md
    print "| Benchmark | min | avg |"                                          >> md
    print "|-----------|-----|-----|"                                          >> md
}
{
    name = $1; gsub(/:/, "", name)
    avg  = $2
    minv = $4; gsub(/^\(min=/, "", minv)
    printf "%s,%s,%s,%s,%s,%s\n", ts, commit, branch, name, to_ns(minv), to_ns(avg) >> hist
    printf "| `%s` | %s | %s |\n", name, minv, avg                            >> md
}
'

echo "Wrote $HISTORY and $MD"
